version: "3"

services:
  backend-flask:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    networks:
      - frontend
      - mongodb
    volumes:
      - backend:/var/backend
    ports:
      - "5000:5000"

  data_ingestion-flask:
    build:
      context: ./data_ingestion
      dockerfile: Dockerfile
    container_name: data_ingestion
    volumes:
      - frontend:/var/data_ingestion
    networks:
      - frontend
    ports:
      - "5001:5001"

  mongodb:
    build: ./mongodb
    container_name: mongodb
    restart: unless-stopped
    networks:
      - mongodb
    volumes:
      - mongodbdata:/data
    ports:
      - "27017:27017"

  webserver:
    build: ./nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - backend-flask
      - data_ingestion-flask
    networks:
      - frontend
volumes:
  mongodbdata:
    driver: local
  backend:
    driver: local
  frontend:
    driver: local
  nginxdata:
    driver: local

networks:
  frontend:
    driver: bridge
  mongodb:
    driver: bridge
